trigger:
  branches:
    include:
      - develop
      - main

pool:
  vmImage: ubuntu-latest

variables:
  imageRepository: career-app
  containerRegistry: careeracr12345.azurecr.io
  dockerfilePath: Dockerfile
  tag: $(Build.BuildId)

stages:

- stage: Build
  displayName: Build and Scan
  jobs:
  - job: BuildAndScan
    steps:
    - checkout: self

    - task: SonarCloudPrepare@3
      inputs:
        SonarCloud: 'SonarCloudConnection'
        organization: 'saishekar555'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: 'saishekar555_career-compass-ai'
        cliProjectName: 'career-compass-ai'
        cliSources: '.'

    - task: SonarCloudAnalyze@3

    - task: SonarCloudPublish@3
      inputs:
        pollingTimeoutSec: '300'

    - task: Docker@2
      displayName: Build and Push Docker Image
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: career-acr-connection
        tags: |
          $(tag)

- stage: Dev
  displayName: Deploy to Dev
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/develop')

  jobs:
  - deployment: DeployDev
    environment: career-dev

    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - script: |
              pwd
              ls -la
            displayName: Debug Repository Files

          - task: KubernetesManifest@1
            displayName: Deploy to AKS Dev
            inputs:
              action: deploy
              kubernetesServiceConnection: career-aks-connection
              manifests: deployment.yaml
              containers: |
                $(containerRegistry)/$(imageRepository):$(tag)

- stage: Prod
  displayName: Deploy to Prod
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')

  jobs:
  - deployment: DeployProd
    environment: career-prod

    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - script: |
              pwd
              ls -la
            displayName: Debug Repository Files

          - task: KubernetesManifest@1
            displayName: Deploy to AKS Prod
            inputs:
              action: deploy
              kubernetesServiceConnection: career-aks-connection
              manifests: deployment.yaml
              containers: |
                $(containerRegistry)/$(imageRepository):$(tag)