apiVersion: apps/v1
kind: Deployment
metadata:
  name: career-compass-deployment

spec:
  replicas: 2

  selector:
    matchLabels:
      app: career-compass

  template:
    metadata:
      labels:
        app: career-compass

    spec:
      containers:
      - name: career-compass
        image: career-compass-ai
        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: career-compass-service

spec:
  type: NodePort

  selector:
    app: career-compass

  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080