apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: resumeiq-prod
resources:
  - ../../base
images:
  - name: acrresumeiq.azurecr.io/resumeiq-web
    newTag: stable
replicas:
  - name: resumeiq-web
    count: 5
